"""empty message

Revision ID: 491389738470
Revises: 8e49ced96a22
Create Date: 2021-05-19 22:13:35.003345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491389738470'
down_revision = '8e49ced96a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed is NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
